version: '3'
services:
  app:
    build: ./backend

    container_name: backend-bot

    restart: on-failure

    volumes:
      - ./backend:/backend
    ports:
      - "3978:3978"
    command: python app.py